.\" rng.1 - Copyright (c) 2018, Sijmen J. Mulder
.Dd June 17, 2018
.Dt RNG 1
.Os
.Sh NAME
.Nm rng
.Nd copy a range of lines
.Sh SYNOPSIS
.Nm
[from]:[to]...
.Sh DESCRIPTION
.Nm
copies the specified line ranges from standard input to standard output.
Ranges are specified as inclusive start and end line numbers.
The first line is numbered 1.
.Pp
Ranges may overlap or backtrack,
but this will cause the input to be buffered in its entirety.
.Ar from
must be greater than the previous range's
.Ar to .
.Sh EXAMPLES
Get lines 2 through 5 and 10 until end of a file:
.Pp
.Dl $ rng 2:5 10: <file.txt
.Sh AUTHORS
Originally by
.An Nickolas Burr
.Aq Mt nickolasburr@gmail.com .
Rewritten by
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl .
