.\" rng.1 - Copyright (c) 2018, Sijmen J. Mulder, see LICENSE.md
.Dd June 24, 2018
.Dt RNG 1
.Os
.Sh NAME
.Nm rng
.Nd copy ranges of lines
.Sh SYNOPSIS
.Nm
.Ar range ...
.Sh DESCRIPTION
.Nm
copies the specified line ranges from standard input to standard output.
Ranges can be specified as follows:
.Pp
.Bl -tag -width indent-two -compact
.It "from:to"
Line
.Em from
through
.Em to
(inclusive).
.It "from:"
Line
.Em from
to end of input.
.It ":to"
Start of input to line
.Em end
(inclusive).
.It ":"
The entire input.
.It line
Line
.Em line
only.
.El
.Pp
Line numbers go up from 1 relative to the start of input,
and down from -1 relative to the end of input.
.Pp
Use of negative line numbers, overlapping ranges, or backtracking ranges
causes the file to be buffered in its entirety.
.Sh EXAMPLES
Output lines 2-5 of a file:
.Pp
.Dl "rng 2:5 <file.txt"
.Pp
Output the first three, fifth, and last three lines of a file:
.Pp
.Dl "rng :3 5 -3: <file.txt"
.Pp
Output a file twice:
.Pp
.Dl "rng : : <file.txt"
.Sh AUTHORS
Originally by
.An Nickolas Burr
.Aq Mt nickolasburr@gmail.com .
Rewritten by
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl .
